## https://docs.docker.com/compose/
## https://docs.docker.com/compose/compose-file/

version: "3.8"

services: 

  hostapd:
    container_name: ps5-hostapd
    image: srgi79/ps5-hostapd:latest
    build:
      context: ./build/
      dockerfile: Dockerfile-hostapd
    #volumes: 
    #- hostapd_dnsmasq_data:/config/:ro
    cap_add: 
    - NET_ADMIN
    network_mode: "host"
    environment: 
      WIFI_DEV: wlp0s12f0
  
  dnsmasqd:
    container_name: ps5-dnsmasqd
    image: srgi79/ps5-dnsmasqd:latest
    build:
      context: ./build/
      dockerfile: Dockerfile-dnsmasqd
    #volumes: 
    #- hostapd_dnsmasq_data:/config/:ro
    depends_on: 
      - hostapd
    network_mode: "host"
    cap_add: 
      - NET_ADMIN
      - NET_BROADCAST
    environment: 
      WIFI_DEV: wlp0s12f0

volumes:
  hostapd_dnsmasq_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/ps5-hostap-dnsmasq/config'