const payload_map =
	[
		{
            displayTitle: 'etaHEN-1.4B.bin', 
            description: 'etaHEN-1.4B.bin', 
            fileName: 'etaHEN-1.4B.bin', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'elfldr.elf', 
            description: 'elfldr.elf', 
            fileName: 'elfldr.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'Browser_appCache_remove.elf', 
            description: 'Browser_appCache_remove.elf', 
            fileName: 'Browser_appCache_remove.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'ps5debug.elf', 
            description: 'ps5debug.elf', 
            fileName: 'ps5debug.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'versions.elf', 
            description: 'versions.elf', 
            fileName: 'versions.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'ftps5-np.elf', 
            description: 'ftps5-np.elf', 
            fileName: 'ftps5-np.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'ftps5-p.elf', 
            description: 'ftps5-p.elf', 
            fileName: 'ftps5-p.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'getOsVersion.elf', 
            description: 'getOsVersion.elf', 
            fileName: 'getOsVersion.elf', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
		{
            displayTitle: 'ps5-kstuff-v1.4.bin', 
            description: 'ps5-kstuff-v1.4.bin', 
            fileName: 'ps5-kstuff-v1.4.bin', 
            author: '-', 
            source: '-', 
            version: '-', 
        },
	];